### ISSUE TITLE
After adding a label, I can no longer close the expanded task with ESC

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#202] opened 2020-02-06 13:58 UTC
I would expect exactly that to be possible. Would that make sense?

**Comment by 4jNsY6fCVqZv** [comment] 2020-02-27 19:49
**EDIT** The same applies to the other actions. When I add a due date, a reminder or a checklist.

**Comment by BeatLink** [comment] 2020-07-17 12:14
I've been able to replicate the behaviour myself. It seems to me that upon selecting the label popover, the task gets deselected. 

@alainm23 Would you like to keep this as intended behaviour and thus close the issue as a question? Or would you want to change this behaviour and thus keep the issue open?

**Closed as completed** 2020-09-15 01:19 UTC
