### ISSUE TITLE
Thick black bars around border

### ISSUE THREAD

**Issue by BiegeRelic** [alainm23/planify#440] opened 2020-07-04 09:58 UTC
**Describe the bug**
Thick black bars around border when the app runs on a tiling window manager
**To Reproduce**
1 install on a tiling window manager 
2 run

**Expected behavior**
Thick black bars around border that take up a lot of realeste

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: manjaro i3 
 - Version 20
**Additional context**
the font is messed up and the black border appears in kde as well after a few weeks of install

**Comment by gregflynn** [comment] 2020-07-06 17:26
Looks like a dupe of #268

**Closed as completed** 2020-07-07 16:31 UTC
Labels: Status: Duplicate
