### ISSUE TITLE
Window position and window size should be restored correctly

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#150] opened 2020-01-22 20:18 UTC
**Describe the bug**
Right now both settings do not seem to be remembered.

**To Reproduce**
At will!

**Expected behavior**
Just as I close the application with the x button, I want it to reappear when I restart it via Plank or the application menu.

**Desktop (please complete the following information):**
- OS or DE: elementary OS 5.1 Hera/Pantheon
- Version: v2.0.8

**Comment by 4jNsY6fCVqZv** [comment] 2020-01-30 14:27
The issue sometimes also causes the window to start so small that the action buttons are not displayed.

**Comment by gavr123456789** [comment] 2020-02-05 10:36
I just wanted to create the same issue, but it already exists. Generally bump!

**Comment by alainm23** [comment] 2020-02-06 14:25
Fixed in v2.2, please wait for the update.

**Closed as completed by alainm23** 2020-02-06 14:25 UTC
Labels: Type: Bug

**Comment by 4jNsY6fCVqZv** [comment] 2020-06-27 09:27
@alainm23 Please reopen for Planner 2.4.2.
I just notice that Planner doesn't remember if I have snapped the window to the left or right side of the screen before. Unlike elementary Code does, for example. There this state is remembered.
Can you please improve something for Planner here?

**Comment by aaronjanse** [comment] 2021-05-17 17:06
Hello! I can reproduce this issue on Planner 2.6.9. It makes it difficult to have Planner as a popup, since it gets bigger every time I  open it.

Thank you for writing Planner. It's super exciting to see a great todo application for Linux!

**Comment by alainm23** [comment] 2021-05-17 18:12
@aaronjanse It's a weird bug, I've the same problem in Pop! OS, apparently this is a bug from the elementary OS stylesheet.
