### ISSUE TITLE
Inbox not showing tasks

### ISSUE THREAD

**Issue by tifDev** [alainm23/planify#753] opened 2021-05-31 17:10 UTC
**Describe the bug**
Inbox is not showing tasks, however when I click on the labels menu, they appear.

**To Reproduce**
This appeared after a reboot.

**Expected behavior**
Should be listing.

**Screenshots**
![image](https://user-images.githubusercontent.com/39730484/120224292-18364180-c23b-11eb-808d-c8dce5c4919b.png)
![image](https://user-images.githubusercontent.com/39730484/120224320-27b58a80-c23b-11eb-8319-970d92a7dc9c.png)

**Desktop (please complete the following information):**
- Ubuntu

**Additional context**
I tried to restore everything from `/home/.var/app/com.github.alainm23.planner/` from a backup, but still the same.
It's installed via flatpack.

**Comment by BeatLink** [comment] 2021-06-05 21:45
duplicate of #764

**Closed as completed by BeatLink** 2021-06-05 21:45 UTC
Labels: Status: Duplicate
