### ISSUE TITLE
Project Created On Planner Does Not Show Up In Todoist, but When Created on Todoist Project Does Show Up (Solved)

### ISSUE THREAD

**Issue by freecicero** [alainm23/planify#656] opened 2020-12-31 16:04 UTC
**Describe the bug**
My headline says it all.  When I create a new project on Planner it doesn't get created at Todoist, but new projects on Todoist do show up on Planner.

**To Reproduce**
Create new project on Planner -- does not show up on Todoist after sync.

**Expected behavior**
Should be able to create projects in either location.

I don't currently use Todoist but may give it is try.  I do have a nextcloud account and am looking forward to a sync there, but for the time being am trying to make todoist work.  

This is a great program -- thanks and good luck!

**Comment by alainm23** [comment] 2020-12-31 17:10
Next to the project name there is a button to select the source (Local or Todoist).Try this please, I can't reproduce the bug.
![image](https://user-images.githubusercontent.com/33765137/103419375-cb055500-4b60-11eb-95e1-a5a457a9533d.png)

**Comment by alainm23** [comment] 2020-12-31 17:24
I am currently working for CalDAV support (Nextcloud, Google Tasks) I hope to be able to launch it together with elementary OS 6

**Comment by freecicero** [comment] 2020-12-31 18:02
Ah that was my problem - I did not realize what that icon did!  THANK YOU!    Can I ask this:  Will I run into any problems when you set up Nextcloud support if I go ahead and input all my tasks into the current todoist system?  In other words, will I be able to sync all the existing Todoist entries with Nexcloud, or will they stay forever separate?

**Comment by alainm23** [comment] 2020-12-31 18:08
Todoist and NextCloud services will work together in Planner with the possibility to exchange tasks, use filters and manage them.

**Comment by alainm23** [comment] 2020-12-31 18:10
If the main problem is solved, I will close this issue, Thanks for using Planner.

**Closed as completed by alainm23** 2020-12-31 18:10 UTC
Labels: Type: Bug
