### ISSUE TITLE
Cant build via AUR

### ISSUE THREAD

**Issue by gavr123456789** [alainm23/planify#137] opened 2020-01-20 10:25 UTC
**Describe the bug**
meson.build:38:4: ERROR: Dependency "libecal-1.2" not found, tried pkgconfig and cmake

**To Reproduce**
1. Go to pamac AUR
2. Click on Build
3. See error  `Dependency "libecal-1.2" not found, tried pkgconfig and cmake`
4. ...Profit

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/30507409/72718968-042efa00-3b88-11ea-9942-2394451b4fe7.png)

**Desktop (please complete the following information):**
 - OS or DE: Arch GNOME
 - 3.34

**Additional context**
There is no version libecal 1.2 for arch, there is only 2.0, it can be viewed for example in evolution.  
https://www.archlinux.org/packages/extra/x86_64/evolution-data-server/files/ (ctrl + f + `libecal-2.0`)

**Comment by alainm23** [comment] 2020-01-21 14:34
@yochananmarqos Could you help me with this error please.

**Comment by yochananmarqos** [comment] 2020-01-21 17:00
@gavr123456789 Not having `libecal-1.2` isn't the issue. It looked for `libecal-2.0` first, but since it couldn't find it it looked for `libecal-1.2` and that's where it stopped. 

I can't reproduce the issue. Make sure you're up to date and maybe reinstall `evolution-data-server`:
```
sudo pacman -Syu evolution-data-server
```

**Comment by gavr123456789** [comment] 2020-01-24 16:03
I'll try again tomorrow. I asked the person in my vala chat, and it works too, it's magic. I absolutely have these files.
![image](https://user-images.githubusercontent.com/30507409/73083380-1ee0d600-3edc-11ea-9d7f-0d90cf1ffaec.png)

**Comment by alainm23** [comment] 2020-01-30 05:11
Any update with this error?

**Comment by gavr123456789** [comment] 2020-01-30 06:16
I have no idea what the problem is, but it's probably just me.  
```
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency libecal-2.0 found: NO (tried pkgconfig and cmake)
Run-time dependency libecal-1.2 found: NO (tried pkgconfig and cmake)

meson.build:34:4: ERROR: Dependency "libecal-1.2" not found, tried pkgconfig and cmake
```  
I have all the libecal files, but pkg config doesn't see them.
```
❯ pkg-config --libs libecal-2.0
Package libical-glib was not found in the pkg-config search path.
Perhaps you should add the directory containing `libical-glib.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libical-glib', required by 'libecal-2.0', not found
```
have no idea

**Comment by BDPeterV** [comment] 2020-01-30 10:56
Have you also installed  "libecal1.2-dev" (not the same as libecal-1.2), which is needed to build the app?

**Comment by gavr123456789** [comment] 2020-01-30 11:39
Yaay, it works after i installed libical  3.0.7-1 (Arch)  
PS In the Flatpack version, I had emoticons, and now it looks like broken UTF codes instead. Is there something specific that I should set up for them?
![image](https://user-images.githubusercontent.com/30507409/73446525-ff2f2f00-436d-11ea-91d3-2d5b3f95d661.png)

-------PSSS--------  
Also, are you sure that this behavior was planned? (the first couple of times before I started shooting it came out smoothly, its very similar to GTK Revealer isnt it)  
![Peek 2020-01-30 14-33](https://user-images.githubusercontent.com/30507409/73446317-95168a00-436d-11ea-8264-f2841ea20875.gif)  
PSP
Your app looks absolutely amazing. I think this is a great example of how GTK can look good on all platforms, even though it doesn't have a native look unlike Qt.

**Comment by alainm23** [comment] 2020-01-30 11:53
1. I'm not sure what's wrong with the character display, could you open a new issue for this please?
2. I'm not sure what's going on here too 😅.

I'm going to close this issue because it's already been solved.

**Closed as completed by alainm23** 2020-01-30 11:53 UTC
Labels: Type: Bug
