### ISSUE TITLE
Sync Labels with Todoist

### ISSUE THREAD

**Issue by Suzie97** [alainm23/planify#588] opened 2020-10-30 07:41 UTC
I use todoist for viewing my tasks on my phone. I get frustrated when I see that the labels created on planner do not sync with Todoist as it is an essential part of my workflow.

If the labels, could sync seamlessly with Todoist, it would be really helpful for me.

**Comment by BeatLink** [comment] 2020-10-31 02:15
Seems like a duplicate of https://github.com/alainm23/planner/issues/104. Head over there and show your wish for this feature by giving a thumbs up

**Closed as completed** 2020-12-19 03:48 UTC
Labels: Status: Duplicate
