### ISSUE TITLE
Feature Request: Boards

### ISSUE THREAD

**Issue by Brin-o** [alainm23/planify#570] opened 2020-10-21 12:03 UTC
**Is your feature request related to a problem? Please describe.**
Todoist introduced a "boards" view where it uses the regular sections to create a Canban board like overview of the project. I think having something like this would be neat as it allows me to use Planner as more of a project management tool alongside a very well organized "todo" list.

**Describe the solution you'd like**
An alternative view option in planner to switch to the board view would be great!

**Describe alternatives you've considered**
I understand this might take a lot of development time, I would like to have this, however an alliterative for everyone that is syncing their projects with todoist is to simply view them on their website if we wish to use the boards feature.

**Comment by skaldebane** [comment] 2020-10-21 13:57
+1! Even though the current version is just perfect for almost all what a person needs (and open-source, free of charge, well supported (Thanks Alain!)), this would be a beautiful thing to see there, though do not expect it to happen very soon...

**Comment by alainm23** [comment] 2020-10-21 22:22
I like the idea, this feature is coming to Planner very soon.

**Comment by Brin-o** [comment] 2020-10-22 07:55
Awesome! If you want I can create some mockups for it. I do think that the "transition" from making sections horizontal towards making them vertical is pretty intuitive tho.

**Comment by alainm23** [comment] 2020-10-22 13:22
Thank you very much, I would like to see your design ideas.

**Comment by BeatLink** [comment] 2020-12-02 21:24
This seems to be a duplicate of #106. As to which issue to keep and which issue to close, I leave that to @alainm23

**Closed as completed** 2020-12-12 05:17 UTC
Labels: Status: Duplicate, Type: Enhancement
