### ISSUE TITLE
Planify crash after adding nextcloud account

### ISSUE THREAD

**Issue by baronleonardo** [alainm23/planify#1147] opened 2024-02-24 04:34 UTC
**Describe the bug**
I tried adding self-hosted nextcloud account to planify, it crashes after 2 seconds from pressing add, and it crashes after then for every start of the app

**To Reproduce**
```
flatpak run io.github.alainm23.planify

** (io.github.alainm23.planify:2): CRITICAL **: 06:29:44.857: services_cal_dav_set_credential: assertion 'message != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 06:29:44.937: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 06:29:45.406: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Json-CRITICAL **: 06:29:46.502: json_object_get_string_member: assertion 'node != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 06:29:46.502: g_variant_new_string: assertion 'string != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 06:29:46.502: g_variant_ref_sink: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 06:29:46.502: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 06:29:46.502: g_variant_get_type_string: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 06:29:46.502: g_settings_set_value: key 'todoist-sync-token' in 'io.github.alainm23.planify' expects type 's', but a GVariant of type '(null)' was given

(io.github.alainm23.planify:2): GLib-CRITICAL **: 06:29:46.502: g_variant_unref: assertion 'value != NULL' failed
**
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
```

**Expected behavior**
no crash should be happen

**Desktop (please complete the following information):**
 - OS or DE: Gnome
 - Version: 45

**Comment by EliasSchriefer** [comment] 2024-03-02 22:51
I think this is a duplicate of #1143

**Closed as completed** 2024-03-18 22:31 UTC
Labels: Type: Bug
