### ISSUE TITLE
Multiple Scrollbars In Preferences Window!

### ISSUE THREAD

**Issue by ProfessorCode212** [alainm23/planify#709] opened 2021-02-24 05:17 UTC
**Describe the bug**
When you open the **Preferences** window in Planner, there are two scrollbars. Furthermore, scrolling down using the mouse wheel is somewhat laggy and doesn't always work. Often, I have to manually drag one of the scrollbars to move down.

**To Reproduce**
1. Go to **Preferences**.
2. Hover over the right-edge of the window.
3. Two scrollbars will appear.
4. Try scrolling down.
5. The window will only scroll down part of the way. (This same issue affects the windows of each _setting_.)

**Expected behavior**
A single scrollbar must appear when hovering over the right corner and scrolling must be smooth.

**Screenshots**
![image](https://user-images.githubusercontent.com/78950242/108951235-9c51b980-768d-11eb-8fa5-7176fbc6ee75.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon
 - Version: 19.3

**Additional context**

**Comment by BeatLink** [comment] 2021-02-25 01:33
This is a duplicate of #693. The issue has been rectified and the fix will be included in a new release. But thank you so much for taking the time to file this bug report. Users like you help to make planner a better app!

**Closed as completed by BeatLink** 2021-02-25 01:33 UTC
