### ISSUE TITLE
Application crashes when moving a newly created task to a different section within a project

### ISSUE THREAD

**Issue by phase1geo** [alainm23/planify#127] opened 2020-01-13 04:31 UTC
- [ ] **Describe the bug**

I created a new task within a project using the Plus button in the bottom.  After which I viewed the detailed view of a task and attempted to move the task to a section within the same project.  When I did this, the application crashed (window disappeared).  When I restarted Planner, the task had properly moved to the requested section.

**To Reproduce**
1. Click on the Plus button
2. Add text to create the task
3. Click on the newly created task to show detail view
4. Click on the '...' menu, select the "Move to Section" menu item and select one of the sections available within the same project.
5. Application crashes

**Desktop (please complete the following information):**
 - elementary OS Pantheon
 - Beta version from GitHub (after pulling TOT)

**Comment by alainm23** [comment] 2020-01-13 15:42
I'm trying to reproduce it but I can't.

**Comment by phase1geo** [comment] 2020-01-13 17:20
I’ll see if I can provide a stack trace...

**Comment by alainm23** [comment] 2020-01-13 17:33
Great.

**Comment by phase1geo** [comment] 2020-01-13 17:51
trevorw@trevorw-KPL-W0X:~/Downloads/planner$ gdb /usr/bin/com.github.alainm23.planner
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/com.github.alainm23.planner...done.
(gdb) run
Starting program: /usr/bin/com.github.alainm23.planner 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffda77a700 (LWP 3272)]
[New Thread 0x7fffd9f79700 (LWP 3273)]
[New Thread 0x7fffd956b700 (LWP 3274)]
[New Thread 0x7fffd8d6a700 (LWP 3275)]
[New Thread 0x7fffcbfff700 (LWP 3276)]

(com.github.alainm23.planner:3224): Gtk-CRITICAL **: 11:48:06.147: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.alainm23.planner:3224): Gtk-CRITICAL **: 11:48:06.230: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed
[New Thread 0x7fffbe5cc700 (LWP 3277)]
[New Thread 0x7fffbddcb700 (LWP 3284)]
[Thread 0x7fffd8d6a700 (LWP 3275) exited]

(com.github.alainm23.planner:3224): Gtk-CRITICAL **: 11:48:07.627: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(com.github.alainm23.planner:3224): Gtk-CRITICAL **: 11:48:07.648: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(com.github.alainm23.planner:3224): GLib-CRITICAL **: 11:48:16.109: Source ID 16 was not found when attempting to remove it
[New Thread 0x7fffd8d6a700 (LWP 3298)]
[Thread 0x7fffd8d6a700 (LWP 3298) exited]

(com.github.alainm23.planner:3224): GLib-GObject-WARNING **: 11:48:24.249: invalid cast from 'WidgetsNewItem' to 'WidgetsItemRow'

Thread 1 "com.github.alai" received signal SIGSEGV, Segmentation fault.
0x0000555555647fe1 in objects_item_get_id (self=0x22a85a47f) at /home/trevorw/Downloads/planner/src/Objects/Item.vala:2
2	    public int64 id { get; set; default = 0; }
(gdb) where
#0  0x0000555555647fe1 in objects_item_get_id (self=0x22a85a47f) at /home/trevorw/Downloads/planner/src/Objects/Item.vala:2
#1  0x000055555563588a in ___lambda590_ (_data111_=0x5555562218f0, widget=0x555555eb48f0) at /home/trevorw/Downloads/planner/src/Views/Project.vala:498
#2  0x0000555555635910 in ____lambda590__gtk_callback (widget=0x555555eb48f0, self=0x5555562218f0) at /home/trevorw/Downloads/planner/src/Views/Project.vala:495
#3  0x00007ffff6896cdb in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x0000555555635966 in __lambda589_ (_data111_=0x5555562218f0) at /home/trevorw/Downloads/planner/src/Views/Project.vala:495
#5  0x0000555555635a42 in ___lambda589__gsource_func (self=0x5555562218f0) at Project.c:4236
#6  0x00007ffff75f1285 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff75f1650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff75f16dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff701de3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x000055555557061e in planner_main (args=0x7fffffffd7c8, args_length1=1) at /home/trevorw/Downloads/planner/src/Application.vala:172
#11 0x0000555555570661 in main (argc=1, argv=0x7fffffffd7c8) at /home/trevorw/Downloads/planner/src/Application.vala:165
(gdb)

**Comment by phase1geo** [comment] 2020-01-13 17:53
Weird.  I'm setting the frame to 0 and running the following command:

(gdb) display *self
2: *self = <error: Cannot access memory at address 0x22a85a47f>

So the pointer to self is non-zero, but the data at the address is not accessible.

**Comment by phase1geo** [comment] 2020-01-13 17:55
I'm compiling with (what I believe is the lastest available version of valac on elementary):

trevorw@trevorw-KPL-W0X:~/Downloads/planner$ valac --version
Vala 0.40.18

**Comment by alainm23** [comment] 2020-04-19 04:27
Some news about this problem, and I tried to reproduce the bug but I can't .

**Comment by alainm23** [comment] 2020-04-20 17:31
I'm going to close this issue because other users don't report the same behavior.

**Closed as completed by alainm23** 2020-04-20 17:31 UTC
Labels: Type: Bug
