### ISSUE TITLE
Window edge gets partly obscured when snapped to edge of the screen

### ISSUE THREAD

**Issue by Andrewsudarikov** [alainm23/planify#178] opened 2020-01-28 09:56 UTC
**Describe the bug**
When the window is snapped to the right side of the workspace, some controls get obscured behind the edge of the screen:

**To Reproduce**
1. Snap the app window to the right half of the workspace by dragging it to the right edge of the screen. 

**Expected behavior**
All controls and the edge of the window should be shown correctly. 

**Screenshots**
![Screenshot from 2020-01-28 12-50-42](https://user-images.githubusercontent.com/18544958/73253328-5d70dc00-41cd-11ea-9adf-49950ff02427.png)

**Desktop (please complete the following information):**
 - Elementary OS
 - Version 5.1

**Comment by 4jNsY6fCVqZv** [comment] 2020-01-28 10:10
Can reproduce the same issue on the left side.
However, I found out that this is because I had to resize the sidebar manually to display my project names in their full length.
Is there a way that Planner behaves in such a way that the window content automatically correlates with the window size? I don't know if I can describe this well. I have also had the experience that I can cut off buttons when I resized the window. Maybe you need some kind of libhandy support in Planner to solve this? https://source.puri.sm/Librem5/libhandy

**Comment by Andrewsudarikov** [comment] 2020-01-28 10:13
> However, I found out that this is because I had to resize the sidebar manually to display my project names in their full length.

BTW, I did not resize the sidebar or the window, I just snapped to the edge of the screen first thing after starting the app for the first time.

**Comment by Andrewsudarikov** [comment] 2020-01-31 14:47
The bug is gone in 2.1.1

**Comment by 4jNsY6fCVqZv** [comment] 2020-01-31 16:51
Not for me, unfortunately.

**Comment by 4jNsY6fCVqZv** [comment] 2020-04-17 17:45
@alainm23 Will this issue be solved by c7c03a5 as well?

And what do you think about creating the support of libhandy as a new ticket?

**Comment by alainm23** [comment] 2020-04-19 04:35
Please try v2.3 and indicate if the problem continues, in my case I cannot reproduce it. 
If I like libhandy and I'm looking at how to integrate it into Planner.

**Comment by alainm23** [comment] 2020-04-19 04:41
I understand your idea, we can make it so that when the entry loses focus the edition is closed.

**Comment by alainm23** [comment] 2020-06-09 21:13
I will close this issue as it is an isolated bug, please reopen it if you can replay it.

**Closed as completed by alainm23** 2020-06-09 21:13 UTC

**Comment by 4jNsY6fCVqZv** [comment] 2020-06-27 09:15
With Planner 2.4.2 I see the issue solved for me as well.
