### ISSUE TITLE
Sorting tasks in label view by drag & drop

### ISSUE THREAD

**Issue by omega3** [alainm23/planify#605] opened 2020-11-06 12:52 UTC
In project view it is possible to sort tasks by drag & drop. I wish it was possible also for label view.

**Comment by BeatLink** [comment] 2020-11-07 14:44
It is possible to drag and drop labels from the settings page but not in the label menu on a specific task. So you would need to go to settings to reorder the labels.

**Comment by BeatLink** [comment] 2020-11-07 14:45
It would be up to @alainm23  whether he would want to declare the above behaviour as intended, or move to change it.

**Comment by omega3** [comment] 2020-11-07 17:57
I am asking about sorting tasks, not labels.

When you click on label in left panel you have label view where are listed all tasks that have this particular label. And I want to sort them by drag and drop.

**Comment by BeatLink** [comment] 2020-12-02 21:14
Hmm, Planner already has sort functionality built in, but only for projects. Whether a feature will be implemented to allow sorting for quick find views would be up to @alainm23

**Comment by alainm23** [comment] 2024-04-28 11:00
I'm not sure I work on this, the labels view works like a filter and is constantly changing. I will close this issue because it is old, if you consider it necessary create it again. Thank you.

**Closed as completed by alainm23** 2024-04-28 11:00 UTC
Labels: Type: Enhancement
