### ISSUE TITLE
Moving a task with a subtask can lead to data loss

### ISSUE THREAD

**Issue by Riksu9000** [alainm23/planify#1239] opened 2024-04-08 06:12 UTC
**Describe the bug**
When moving a task with a subtask to another project, the move seems to succeed, but the number of tasks in a project doesn't match up. When deleting the "empty" project, the subtask disappears from the other project.

**To Reproduce**
1. Create two projects
2. Create a task with a subtask in one project
3. Drag the parent task from one project to the other

**Screenshots**
https://github.com/alainm23/planify/assets/37774658/26127ea0-bd17-4059-822a-1926af5dbdaf

**Desktop (please complete the following information):**
 - Fedora, Planify master

**Additional context**
I found this bug while trying to move multiple tasks between projects. I tried to select all, but the move still applied to just one task, so I tried to be clever and created one task that holds multiple tasks. As I tried to move the subtasks out of the parent task, the tasks sometimes disappeared from both projects and sometimes restarting the app made some visible.

**Comment by blackwolf12333** [comment] 2024-04-09 08:20
@alainm23 I think this is a duplicate of https://github.com/alainm23/planify/issues/1234

**Closed as completed** 2024-04-14 11:09 UTC
Labels: Type: Bug
