### ISSUE TITLE
Ability to archive project

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#664] opened 2021-01-06 14:35 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently there is no support for archiving or viewing archived projects. This is a Todoist Feature

**Describe alternatives you've considered**
Ignore the archived project or deleting them

**Additional context**
The app should be able to sync the archive state

**Comment by BeatLink** [comment] 2021-03-13 10:37
This seems like a duplicate of #579. Feel free to head there and give your input. I'll go ahead and close this issue

**Closed as completed by BeatLink** 2021-03-13 10:37 UTC
Labels: Status: Duplicate, Type: Enhancement
