### ISSUE TITLE
elementaryOS AppCenter version still stuck at 2.6.3

### ISSUE THREAD

**Issue by skaldebane** [alainm23/planify#695] opened 2021-02-06 23:55 UTC
It's been a while since the official elementaryOS version has been updated, and now it's stuck at 2.6.3. I heard it's caused because of problems with AppCenter, and I thought it'd be good to track any progress on this through this issue.

**Comment by alainm23** [comment] 2021-02-07 14:37
Apparently the problem is solved and Planner 2.6.9 is still in revision.
![image](https://user-images.githubusercontent.com/33765137/107149688-ff222180-6927-11eb-963e-28f777d71b51.png)

**Comment by skaldebane** [comment] 2021-02-08 20:37
Great 👍️ I'll close this issue as soon as it gets updated.

**Comment by skaldebane** [comment] 2021-02-13 16:59
It's taken a little too long I guess... Nothing yet.

**Comment by skaldebane** [comment] 2021-02-19 23:42
It's been 2 weeks and... still nothing! I will probably start using the Flatpak version instead (it's slower but I guess it's worth it).

**Comment by BeatLink** [comment] 2021-03-04 23:22
As mentioned in https://github.com/alainm23/planner/issues/555#issuecomment-790640638, AppCenter updates have been paused momentarily. In the meantime, you can use flatpack. I will go ahead and close the issue for now. If Elementary OS 6 has been released and AppCenter updates are still held, I will reopen this issue.

**Closed as completed by BeatLink** 2021-03-04 23:22 UTC
Labels: Type: Bug
