### ISSUE TITLE
High CPU Usage on Ubuntu

### ISSUE THREAD

**Issue by kbdlnx** [alainm23/planify#665] opened 2021-01-07 12:58 UTC
**Describe the bug**
As long as Planner is running, there is CPU usage 40-60% which also spins up the fan more than usual.

**To Reproduce**
As long as you open Planner it will happen on the latest version

**Expected behavior**
Planner functions fine however, CPU usage is a bit too high. Before this update, it was 3-10%

**Screenshots**
https://imgur.com/tSXdyPf

**Desktop (please complete the following information):**
 - Ubuntu [gnome]
 - Version [20.10]

**Additional context**

**Comment by skaldebane** [comment] 2021-01-08 01:31
Potential duplicate for #569 . This issue has existed even on previous versions.

**Comment by BeatLink** [comment] 2021-03-04 23:14
Closing as duplicate of #569. Feel free to head there to give your input on the problem

**Closed as completed by BeatLink** 2021-03-04 23:14 UTC
Labels: Type: Bug, Status: Duplicate
