### ISSUE TITLE
Endless waiting when adding to Today.

### ISSUE THREAD

**Issue by gavr123456789** [alainm23/planify#197] opened 2020-02-01 10:42 UTC
**Describe the bug**
Endless waiting when adding to Today.

**To Reproduce**
1. Go to Today
2. Try to add new task
3. May be it will endless
4. May be not

**GIF**
![bug](https://user-images.githubusercontent.com/30507409/73590841-4517fe80-44f8-11ea-8210-2d7993504c18.gif)

**Desktop (please complete the following information):**
 - gnome arch
 - From AUR

**Additional context**
I think if you can't find the problem, you should at least add a timeout to add the task.

**Comment by 4jNsY6fCVqZv** [comment] 2020-02-01 10:56
Cannot reproduce the issue with the latest AppCenter version.

A question I have to ask myself though: Shouldn't Today view and Upcoming view simply show what/if tasks are there? Maybe it should not be possible to create tasks in the Today view. Especially since I noticed while testing this issue here that only with this possibility further errors in the interaction with the Inbox view occur.

**Comment by robertkern** [comment] 2020-02-06 23:03
Just adding my voice here - I am experiencing the same (or similar) issue. The first time I add a task from the Today view it works fine, then the next time i try to add a task it looks like it's still adding the previous task (but the previous task was already saved). It doesn't seem to happen in over views (other than Today) but I usually add new tasks via Today.

**Comment by alainm23** [comment] 2020-02-07 21:31
Fixed in version 2.2

**Closed as completed** 2020-02-07 21:32 UTC
Labels: Type: Bug
