### ISSUE TITLE
Can't find the plugin area to turn on CALDAV support

### ISSUE THREAD

**Issue by therealrobster** [alainm23/planify#872] opened 2022-02-24 10:21 UTC
Hi there,

Using FLATPAK 3.0.4 version of Planner.

I have my own Baikal CALDAV server and am looking for the plugin area of Planner, so I can turn on CALDAV support and enter the custom URL etc of my server.

I read by searching this github area that it's in the settings, however my settings looks like this:

![image](https://user-images.githubusercontent.com/15485920/155505492-fc0688de-de1b-4045-b3d1-a0341a89ba6d.png)

I'm not sure exactly where to go from here.  Any suggestions would be greatly appreciated.

Thank you

POPOS 20.04
Planner Flatpak 3.0.4

**Comment by therealrobster** [comment] 2022-02-25 00:45
Further to this,  I've got 3.0.6 on a debian machine and still the same thing.  No area that I can find anywhere to add a CALDAV url.

**Comment by alainm23** [comment] 2022-02-25 03:20
CalDAV support will be available very soon.

**Comment by HansCronau** [comment] 2022-03-20 20:17
@alainm23, that explains a lot! I was confused when I saw mentions of Planner 3, but no fix to #555. Does this mean this issue is basically a duplicate of #555?

**Closed as completed** 2022-04-09 23:19 UTC
