### ISSUE TITLE
Task creation fails with Todoist syncronization enabled

### ISSUE THREAD

**Issue by juesem** [alainm23/planify#938] opened 2022-09-25 21:41 UTC
Creation of task and projects fails using syncronization with Todoist. The new task or project disappears after pressing the enter key. Nevertheless the task appears in the Todoist app of my iPhone.

**Desktop (please complete the following information):**
 - Fedora 36 with Gnome 42 (Wayland)

**Additional context**
- Flatpak version of planner used

**Comment by jo-jstrm** [comment] 2022-10-06 14:22
This is a duplicate of #927.

**Closed as not planned** 2022-11-26 14:28 UTC
Labels: Status: Duplicate
