### ISSUE TITLE
Enable: Pics Drag and Drop [png, jpeg]

### ISSUE THREAD

**Issue by theunclemez** [alainm23/planify#557] opened 2020-10-07 23:39 UTC
I'm everyday halfway between graphic design and other IT task and while building my projects tasks and notes I noticed I couldn't drag and drop a pic (it's an essential part of my work)
So this made me go try to find another way and the simplest one was to copy-paste link to pics ... bit of too much efforts !

My entry as a solution would be to expand the possibilities and allow dragn'drop of pics in common format and maybe of other common file type.
Not going to ask you make it possible to create mood board using Planner but if it possible then please it would help a lot.

If not possible to dragn'drop files in there then link preview can make it too.
copy paste link and the app would sync and display the object linked to the url.

**Comment by BeatLink** [comment] 2020-10-12 04:21
Seems like a duplicate of https://github.com/alainm23/planner/issues/488 except for the drag and drop bit. You can go over to that issue and add on the drag and drop feature to that feature request.

**Closed as completed** 2020-10-23 09:37 UTC
