### ISSUE TITLE
Planner Doesn't Run On Startup

### ISSUE THREAD

**Issue by ProfessorCode212** [alainm23/planify#763] opened 2021-06-03 23:31 UTC
**Describe the bug**
Selecting _Run on startup_ doesn't actually make _Planner_ launch at startup.

**To Reproduce**
1. Go to _General_
2. Toggle _Run on startup_.
3. Restart the computer.
4. Planner doesn't launch.

**Expected behavior**
Planner launches at startup when _Run on startup_ is enabled.

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint (Cinnamon)
 - Version: 19.3

**Additional context**
I've installed _Planner_ as a Flatpak.

**Comment by Ph0enix001** [comment] 2021-07-22 04:14
@ProfessorCode212  For me the problem is when I start Planner after starting my computer, I get a plain theme color without anything. I have to kill the application once and start it again for it to work normally.

**Comment by ProfessorCode212** [comment] 2021-07-22 04:22
@Ph0enix001 You should probably create a new issue since our issues are quite different.

**Comment by Ph0enix001** [comment] 2021-07-22 04:33
@ProfessorCode212 I have created a new issue.

**Comment by alainm23** [comment] 2023-06-26 23:56
This bug was fixed in Planify 4.1.

**Closed as completed by alainm23** 2023-06-26 23:56 UTC
