### ISSUE TITLE
Hangs a launch

### ISSUE THREAD

**Issue by wout** [alainm23/planify#320] opened 2020-04-23 07:39 UTC
**Describe the bug**
After upgrading to 2.3.2, planner no longer launches. The icon shows the app is open, but no window appears. Looking at the syslog, the app seems to be in a loop, spawning a huge amount of (the same) error messages.

**To Reproduce**
1. Open planner
2. It hangs

**Expected behavior**
Should launch.

**Screenshots**
![planner-bug](https://user-images.githubusercontent.com/107324/80071932-67407c00-853d-11ea-819e-51a7f8bf7b92.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/107324/80072197-d027f400-853d-11ea-8b42-834151d044ed.png)

**Comment by marcosegato** [comment] 2020-04-23 08:02
Probably duplicate of #319, waiting for 2.3.3 release in AppCenter

**Comment by snowparrot** [comment] 2020-04-23 08:56
Can confirm.

**Comment by alainm23** [comment] 2020-04-23 09:32
The bug was fixed, wait for update 2.3.3 please.

**Closed as completed** 2020-04-23 09:32 UTC
Labels: Status: Duplicate
