### ISSUE TITLE
Weird (titlebar) buttons

### ISSUE THREAD

**Issue by Leon0402** [alainm23/planify#583] opened 2020-10-29 10:29 UTC
**Describe the bug**
The buttons look kinda weird and have a strange hover effect. This affects also dialog buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/33933142/97556356-a3b3cf80-19d9-11eb-8a82-063970acbb09.png)
![image](https://user-images.githubusercontent.com/33933142/97556509-e4134d80-19d9-11eb-8eaa-b0162e5008bf.png)

**Desktop (please complete the following information):**
 - OS or DE: Plasma
 - Version 2.5.7

**Comment by BeatLink** [comment] 2020-12-02 21:17
From the looks of things this may be a problem with your DE, plasma. The buttons look like the top left quarter of the plasma DE window controls merged with the built in ones on planner.

Perhaps you could file a bug report with KDE?

**Comment by Leon0402** [comment] 2020-12-02 21:30
It probably is, there were just similar reports today with other gtk apps (like firefox ... although firefox just works fine for me and any other gtk app I have as well). 

Someone wanted to open a bug report, if it doesn't happen, I will open one.

**Comment by BeatLink** [comment] 2020-12-02 21:32
Great. Are you okay with closing this issue until you hear from KDE that the issue is specific to planner?

**Closed as completed** 2022-02-11 13:42 UTC
Labels: Type: Bug
