### ISSUE TITLE
Notes parser has trouble parsing URLs with queries and plus signs

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#524] opened 2020-09-22 21:13 UTC
**Describe the bug**

**To Reproduce**
1. Create a new task
2. Edit the task note
3. Add a url that includes a query section with plus signs. 
    * In my case, I was trying to use https://disboard.org/search?keyword=linux+programming.
4. Add a url immediately after, or on a new line
    * For this one I used https://disboard.org/search
5. Notice that the parser either:
    - Doesnt show the content
    - Deletes the content
    - Displays it broken similar to #515 
    - parse the URL properly, but everything after the + sign is excluded from the URL

**Expected behavior**
URLs with plus signs should be parsed normally

**Screenshots**
The text that causes the parsing issue (pasted as is)
![image](https://user-images.githubusercontent.com/47278150/93937687-c7566c80-fced-11ea-8551-ac0f89a3929f.png)

How the same task appears unfocused
![image](https://user-images.githubusercontent.com/47278150/93938068-55325780-fcee-11ea-8b98-f7eb9cd2e689.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 20
 - Version https://github.com/alainm23/planner/commit/603a2334b9299519a559950527dfde38dc1c78f9

**Additional context**
I will try compiling the latest build to see if the issue is still persistent. I will message in a few

**Comment by BeatLink** [comment] 2020-09-22 21:32
I was running planner in a terminal when i caught this output

> (com.github.alainm23.planner:2): Gtk-WARNING **: 16:07:12.356: Failed to set text '<a href="<a href="https://disboard.org/search">https://disboard.org/search</a>?keyword=linux+programming"><a href="https://disboard.org/search">https://disboard.org/search</a>?keyword=linux+programming</a>
<a href="https://disboard.org/search">https://disboard.org/search</a>
' from markup due to error parsing markup: Error on line 1 char 33: Odd character “/”, expected a '=' after attribute name “https:” of element “a”

**Comment by BeatLink** [comment] 2020-09-22 21:37
Issue is reproducible on latest build https://github.com/alainm23/planner/commit/e538dcf4397a078e97be8db64c4ac300f5f087d8

**Comment by alainm23** [comment] 2020-09-22 21:49
I can't reproduce the bug with my current version, try updating Planner to the latest version of the repository.
![image](https://user-images.githubusercontent.com/33765137/93941142-692c8800-fcf3-11ea-973b-5721e62ffba9.png)

**Comment by alainm23** [comment] 2020-09-22 22:11
This is a very peculiar bug, it's because the same base URL is being used and causing the URL converter to get confused, I'll see how I can solve it.

**Comment by BeatLink** [comment] 2020-09-22 23:33
Thanks! Keep me posted please.

**Comment by alainm23** [comment] 2023-01-29 13:06
Fixed in the new version of Task Planner

**Closed as completed by alainm23** 2023-01-29 13:06 UTC
Labels: Type: Bug
