### ISSUE TITLE
Add more options for repeating tasks

### ISSUE THREAD

**Issue by StoicDeveloper** [alainm23/planify#741] opened 2021-05-14 03:43 UTC
Many repeating tasks need to be accomplished every second day, or other currently unsupported intervals. Currently the only options for repeated tasks is every day, week, month, and year. 

Possible solutions include:
- selecting interval of day, week, month, year
- selecting the number of days to skip
- selecting the number of repetitions

So for example, I could select an interval of 2 days, for a total of 10 events, so that the task would appear 10 times over the next 20 days.

**Comment by BeatLink** [comment] 2021-05-15 03:24
Duplicate of #389

**Closed as completed** 2021-05-15 13:05 UTC
Labels: Status: Duplicate
