### ISSUE TITLE
Feature request: Custom schedule cycles for repeating tasks

### ISSUE THREAD

**Issue by esszed** [alainm23/planify#537] opened 2020-09-28 00:29 UTC
I think the repeating tasks could really be more powerful with ability to set your own repeating cycles. For example setting task for every other day or having one task schedule for every Wednesday and Friday etc.

**Comment by BeatLink** [comment] 2020-09-28 22:38
This seems like a duplicate of my issue here: https://github.com/alainm23/planner/issues/389

Maybe you could head on over and show your support with a thumbs up?

**Comment by esszed** [comment] 2020-09-28 22:40
#389  Duplicate

**Closed as completed** 2020-09-28 22:39 UTC
