### ISSUE TITLE
add a pomodoro plugin to tasks

### ISSUE THREAD

**Issue by mlaarebi** [alainm23/planify#749] opened 2021-05-20 13:02 UTC
**Is your feature request related to a problem? Please describe.**
When working on a project, having a pomodoro integrated in the app can help reduce time and effort switching btw several apps

**Describe the solution you'd like**
a plugin that the user can enable easily.

**Comment by BeatLink** [comment] 2021-05-21 13:32
Duplicate of https://github.com/alainm23/planner/issues/315

**Comment by BeatLink** [comment] 2021-05-21 13:33
I'm going to go ahead and close this issue. You can head on over to #315 and show your support!

**Closed as completed by BeatLink** 2021-05-21 13:33 UTC
Labels: Status: Duplicate
