### ISSUE TITLE
Error when selecting colour for new project

### ISSUE THREAD

**Issue by Jane2213** [alainm23/planify#229] opened 2020-02-17 02:09 UTC
**Describe the bug**
getting a status code:403 when adding a colour to a new project

**To Reproduce**
1. create a new project
2. Right click the new project and hit edit 
3. pick a colour

**Expected behavior**
no error codes

**Screenshots**
![image](https://user-images.githubusercontent.com/46205771/74618492-a692bc80-50f7-11ea-9891-ad0fca118472.png)

**Desktop (please complete the following information):**
 - elementary os
 - Version 2.1.1

**Comment by 4jNsY6fCVqZv** [comment] 2020-02-18 07:45
Probably a duplicate of https://github.com/alainm23/planner/issues/198.

**Closed as completed** 2020-02-18 12:26 UTC
Labels: Status: Duplicate

**Comment by alainm23** [comment] 2020-02-18 12:27
I will start with Planner as a new installation and see if I can reproduce the bug.
